name: Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      
      - name: Prepare the environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install gperf cpio gcc gcc-multilib g++-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python ssh wget tmate

      - name: Running tmate
        run: |
          tmate -F
